# Generated by Django 4.1.3 on 2023-03-09 02:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('acommodations', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accommodation',
            old_name='roooms',
            new_name='rooms_number',
        ),
    ]
